### ISSUE TITLE
Support for Mendix 7?

### ISSUE THREAD

**Issue by abhishekdevaraj** [tieniber/KeyboardShortcut#5]
Hi,

First of all I would like to appreciate the time and effort put into making this awesome widget. But I would like to know if the support for this widget will be extended to Mendix 7. That would be really helpful. Thanks again for all your hardwork.

**Comment by tieniber** [comment]
Does it not work in Mendix 7? If not, what is the issue?

**Comment by abhishekdevaraj** [comment]
![image](https://user-images.githubusercontent.com/42667723/44913882-30a46500-ad4c-11e8-9b3f-79ad98f73a7d.png)

![image](https://user-images.githubusercontent.com/42667723/44913936-4dd93380-ad4c-11e8-8723-ead3dc47cdf8.png)

**Comment by tieniber** [comment]
Oddly, I could not reproduce this error although I see why it may have occurred. At line 166, a variable called "code" is referenced before it's declared. I've added an explicit declaration. Can you download the latest widget in the /dist/ folder and try it?

**Comment by abhishekdevaraj** [comment]
Hi Tieniber,

It's working fine now. Thanks for looking into this. Appreciate it.

**Comment by tieniber** [comment]
Great. New release just hit the App Store.
